# Application configuration
app:
  name: "githappy"
  description: "Personal Changelog API to track your life like a GitHub project"

# Environment configuration
environment:
  development:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  testing:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  production:
    debug: false
    cors_origins:
      - https://example.com